# Config for a DGX-1 V100 reporting to production schema.
test_harness: 'tf_cnn_benchmark'
test_environment: 'brain-lab'
# System basics
platform: 'NVIDIA'
platform_type: 'DGX-1 (V100)'

# Build type info
channel: NIGHTLY
build_type: OTB

# reporting
report_auth: 'brain_lab_benchmarks.json'
report_project: 'google.com:tensorflow-performance'
report_dataset: 'benchmark_results'
report_table: 'result'

# tf-cnn-benchmarks
tf_cnn_bench_configs:
  - benchmark_harness/oss_bench/test_runners/tf_cnn_bench/configs/io_warmup_real.yaml
  - benchmark_harness/oss_bench/test_runners/tf_cnn_bench/configs/v100_training_resnetv1.yaml
  - benchmark_harness/oss_bench/test_runners/tf_cnn_bench/configs/v100_training_resnetv1_5.yaml

