# Default config assumes usage of docker and local GPU at least GTX1080
test_harness: 'mxnet_benchmark'
test_environment: 'brain-lab'
# System basics
platform: 'NVIDIA'
platform_type: 'DGX-1 (V100)'

# reporting
report_auth: 'brain_lab_benchmarks.json'
report_project: 'google.com:tensorflow-performance'
report_dataset: 'benchmark_results'
report_table: 'result'

# mxnet tests to run.
mxnet_tests:
  - renset50v1_64_gpu_1
  - renset50v1_64_gpu_8
  - renset50v1_128_gpu_1_fp16
  - renset50v1_128_gpu_8_fp16
