# Config for a AWS reporting to production schema.
test_harness: 'tf_cnn_benchmark'
test_environment: 'gce'
# System basics
# platform is not part of the key in the dashboard.
platform: 'gce'
platform_type: 'v100-Alpha'

# reporting
report_auth: 'benchmark_upload_gce.json'
report_project: 'google.com:tensorflow-performance'
report_dataset: 'benchmark_results'
report_table: 'result'

# tf-cnn-benchmarks
tf_cnn_bench_configs:
  - benchmark_harness/oss_bench/test_runners/tf_cnn_bench/configs/dgx_v100_real.yaml
  - benchmark_harness/oss_bench/test_runners/tf_cnn_bench/configs/dgx_v100.yaml
  - benchmark_harness/oss_bench/test_runners/tf_cnn_bench/configs/dgx_io_test.yaml
  - benchmark_harness/oss_bench/test_runners/tf_cnn_bench/configs/dgx_io_test_real.yaml
