# Config for a z420 with GTX-1080 reporting to production schema.
test_harness: 'tf_cnn_benchmark'
test_environment: 'google-workstation'
# System basics
platform: 'workstation'
platform_type: 'z420'

# reporting
report_auth: 'tensorflow_performance_upload_tb.json'
report_project: 'google.com:tensorflow-performance'
report_dataset: 'benchmark_results'
report_table: 'result'

# tf-cnn-benchmarks
tf_cnn_bench_configs:
  - benchmark_harness/oss_bench/test_runners/tf_cnn_bench/configs/workstation_gtx1080.yaml
