# Default config assumes usage of docker and local GPU at least GTX1080
test_harness: 'mxnet_benchmark'
test_environment: 'google-workstation'
# System basics
platform: 'workstation'
platform_type: 'z420'

# reporting
report_auth: 'tensorflow_performance_upload_tb.json'
report_project: 'google.com:tensorflow-performance'
report_dataset: 'benchmark_results'
report_table: 'result'

# mxnet tests to run.
mxnet_tests:
  - renset50v1_32_gpu_1
  - renset50v1_32_gpu_1_fp16
