# Default config assumes usage of docker and local GPU at least GTX1080
test_environment: 'google-workstation'
# System basics
platform: 'workstation'
platform_type: 'z420'

# reporting
report_auth: 'tensorflow_performance_upload_tb.json'
report_project: 'google.com:tensorflow-performance'
report_dataset: 'benchmark_results'
report_table: 'result'

# reporting
report_auth: 'nightly_benchmark_dev.json'
report_project: 'google.com:tensorflow-performance'
report_dataset: 'benchmark_results_dev'
report_table: 'result'

# pytorch tests to run.
pytorch_tests:
  - renset50_32_gpu_1_real

input_threads: 6
