args: {batch-size: 32, disp-batches: 5, dtype: float32, gpus: '0',
  image-shape: '3,224,224', kv-store: device, network: resnet-v1, num-epochs: 1,
  num-layers: 50}

test_id: resnet50.gpu_1.32.real
batch_size: 32
gpus: 2
