# Config for a DGX-1 V100 reporting to production schema.
test_harness: 'tf_cnn_benchmark'
test_environment: 'brain-lab'
# System basics
platform: 'NVIDIA'
platform_type: 'DGX-1 (V100)'

# reporting
report_auth: 'nightly_benchmark_dev.json'
report_project: 'google.com:tensorflow-performance'
report_dataset: 'benchmark_results_dev'
report_table: 'result'

# tf-cnn-benchmarks
tf_cnn_bench_configs:
  - benchmark_harness/oss_bench/test_runners/tf_cnn_bench/configs/dgx_v100.yaml

tf_models_tests:
  - 'renset50v2_64_gpu_1_real'
  - 'renset50v2_64_gpu_8_real'

# Args for tf_models_tests.  Seen by all test harnesses as well.
input_threads: 30
