# General settings
repeat: 3

# Worker settings override
num_batches: 100
nodistortions: FLAG_ONLY
datasets_use_prefetch: False

sub_configs:
  - 'tests/resnet/128/resnet50.1_gpu.forward_only.128.ps_gpu.cuda_visible_0.fp16.yaml'
  - 'tests/resnet/128/resnet50.1_gpu.128.ps_gpu.cuda_visible_0.fp16.yaml'
  - 'tests/resnet/128/resnet50.8_gpu.128.replicated_nccl.prefetch.fp16.yaml'
  - 'tests/resnet/128/resnet50.8_gpu.128.replicated_hierarchical_repacking.prefetch.fp16.yaml'
  - 'tests/resnet/256/resnet50.1_gpu.256.ps_gpu.cuda_visible_0.fp16.yaml'
  - 'tests/resnet/256/resnet50.8_gpu.256.replicated_hierarchical_repacking.prefetch.fp16.yaml'
  - 'tests/resnet/256/resnet50.8_gpu.256.replicated_nccl.prefetch.fp16.yaml'
  - 'tests/resnet/256/resnet50.2to4_gpu.256.replicated_hierarchical_repacking.prefetch.fp16.yaml'
  - 'tests/resnet/256/resnet50.2to4_gpu.256.replicated_nccl.fp16.yaml'
