# General settings
repeat: 1

# Worker settings override
num_batches: 20

sub_configs:
  - 'tests/resnet/resnet50.1_gpu.32.ps_gpu.yaml'
  - 'tests/resnet/resnet50.1_gpu.32.replicated_nccl.yaml'
  - 'tests/vgg/vgg16.1_gpu.32.ps_gpu.yaml'
  - 'tests/vgg/vgg16.1_gpu.32.ps_cpu.yaml'
