# General settings
repeat: 3

# Worker settings override
num_batches: 100
nodistortions: FLAG_ONLY

sub_configs:
  - 'tests/resnet/resnet50.1_gpu.64.ps_gpu.yaml'
  - 'tests/resnet/resnet50.8_gpu.64.replicated_nccl.yaml'
  - 'tests/resnet/resnet50.8_gpu.64.replicated_hierarchical_nolayers.yaml'
  - 'tests/resnet/resnet50.8_gpu.64.ps_cpu.yaml'
  - 'tests/resnet/resnet50.1_gpu.128.ps_gpu.yaml'
  - 'tests/resnet/resnet50.8_gpu.128.replicated_nccl.yaml'
  - 'tests/resnet/resnet50.8_gpu.128.ps_cpu.yaml'
  - 'tests/vgg/vgg16.1_gpu.64.ps_gpu.yaml'
  - 'tests/vgg/vgg16.8_gpu.64.replicated_nccl.yaml'
  - 'tests/vgg/vgg16.1_gpu.128.ps_gpu.yaml'
  - 'tests/vgg/vgg16.8_gpu.128.replicated_nccl.yaml'
  - 'tests/vgg/vgg16.8_gpu.64.replicated_hierarchical_repacking'
  - 'tests/vgg/vgg16.8_gpu.64.replicated_hierarchical'
  - 'tests/resnet/resnet50.1_gpu.128.ps_gpu.fp16.yaml'
  - 'tests/resnet/resnet50.8_gpu.128.replicated_nccl.fp16.yaml'
  - 'tests/resnet/resnet50.8_gpu.128.ps_cpu.fp16.yaml'
  - 'tests/resnet/resnet50.8_gpu.128.replicated_hierarchical_nolayers.fp16.yaml'
  - 'tests/resnet/resnet50.8_gpu.128.replicated_hierarchical.fp16'
  - 'tests/resnet/resnet50.8_gpu.128.replicated_hierarchical_repacking.fp16'
  - 'tests/resnet/resnet50.8_gpu.128.replicated_hierarchical_repacking_nolayers.fp16'
