# General settings
repeat: 3

# Worker settings override
num_batches: 100
nodistortions: FLAG_ONLY
sub_configs:
  - 'tests/resnet/resnet50.1_gpu.64.ps_gpu.yaml'
  - 'tests/resnet/resnet50.1_gpu.64.ps_cpu.yaml'
  - 'tests/resnet/resnet50.4_gpu.64.ps_gpu.yaml'
  - 'tests/resnet/resnet50.8_gpu.64.replicated_nccl.yaml'
  - 'tests/resnet/resnet50.8_gpu.64.ps_cpu.yaml'
  - 'tests/vgg/vgg16.1_gpu.64.ps_gpu.yaml'
  - 'tests/vgg/vgg16.8_gpu.64.replicated_nccl.yaml'
