# General settings
repeat: 3

# Worker settings override
nodistortions: FLAG_ONLY
# Data directory mounted in the docker
data_dir: '/data/imagenet'
# Causes .real to be appended to all test_ids if data_dir is found.
test_id_hacks: True

sub_configs:
  - 'tests/alexnet/alexnet.8_gpu.512.replicated_hierarchical_repacking.yaml'
  - 'tests/trivial/trivial.8_gpu.128.independent.yaml'
  - 'tests/trivial/trivial.8_gpu.64.independent.yaml'

