# General settings
repeat: 3

# Worker settings override
num_batches: 100
nodistortions: FLAG_ONLY

# Synthetic tests do not support prefetch and it does not matter.
datasets_use_prefetch: False

sub_configs:
  - 'tests/resnet/256/resnet50.8_gpu.256.replicated_hierarchical_repacking_gcp.fp16.yaml'
  - 'tests/vgg/vgg16.8_gpu.128.replicated_hierarchical_repacking_gcp.yaml'
